#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

REQUIREMENTS="requirements.txt"
VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi
"$PIP" uninstall -y $(pip show setuptools | awk '/^Requires: / {print $2}' | tr ',' '\n') setuptools
"$PIP" install --ignore-installed --index-url 'https://:2024-03-05T16:16:50.957686Z@time-machines-pypi.sealsecurity.io/' setuptools
"$PIP" install -U pip
"$PIP" install --ignore-installed --index-url 'https://:2024-03-05T16:16:50.957686Z@time-machines-pypi.sealsecurity.io/' -r "$REQUIREMENTS"
"$PIP" install --index-url 'https://:2024-03-05T16:16:50.957686Z@time-machines-pypi.sealsecurity.io/' -e .
